global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'node'
    static_configs:
      - targets: ['192.168.31.242:9100']
        labels:
          group: 'node_exporter'

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.31.242:8080']
        labels:
          group: 'cadvisor_group'
