apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod-all
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "1000"]
      envFrom:
      - configMapRef:
          name: user-configmap
  restartPolicy: Never
