apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod-volume
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "1000"]
      volumeMounts:
      - name: user-config-volume
        mountPath: /etc/user-config
  volumes:
  - name: user-config-volume
    configMap:
      name: user-configmap
  restartPolicy: Never
