apiVersion: v1
kind: Pod
metadata:
  name: configmap-test-pod
spec:
  containers:
    - name: busybox-container
      image: busybox:latest
      command: ["sleep", "1000"]
      env:
        - name: ENV_VAR_USERNAME
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: user.name
        - name: ENV_VAR__ID
          valueFrom:
            configMapKeyRef:
              name: user-configmap
              key: user.id
  restartPolicy: Never
